---
exp_name: GRAN
exp_dir: exp/GRAN
runner: GranRunner
use_horovod: false
use_gpu: true
device: cuda:0
gpus: [0]
seed: 1234
dataset:
  loader_name: GRANData
  name: DT
  data_path: data/
  node_order: BFS # k_core/BFS/degree_decent
  train_ratio: 0.9
  dev_ratio: 0.2
  num_subgraph_batch: 61 # number of subgraphs per mini-batch, bigger than num_fwd_pass
  num_fwd_pass: 61
  has_node_feat: true
  is_save_split: false  
  is_sample_subgraph: true # set to true if you want to sample subgraphs
  is_overwrite_precompute: true
model:
  name: GRANMixtureBernoulli  
  num_mix_component: 30
  is_sym: true
  block_size: 1
  sample_stride: 1
  max_num_nodes: 65
  hidden_dim: 128
  embedding_dim: 128
  num_GNN_layers: 3
  num_GNN_prop: 5
  num_canonical_order: 1
  dimension_reduce: true
  has_attention: true
  edge_weight: 1.0e+0
  agg_GNN_method: 'sum' # mean, sum
  relative_training: False
  relative_num: 5
train:
  optimizer: Adam  
  lr_decay: 0.1
  lr_decay_epoch: [200]
  num_workers: 1
  max_epoch: 20000
  batch_size: 1
  display_iter: 100
  snapshot_epoch: 10
  valid_epoch: 50
  lr: 1.0e-4
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_epoch: 5000
  resume_dir: # exp/GRAN/your_exp_folder
  resume_model: model_snapshot_0005000.pth
test:  
  batch_size: 1
  num_workers: 0
  num_test_gen: 9 # number of generated samples  
  is_vis: true
  is_single_plot: false # visualize `num_vis` samples in a single image
  is_test_ER: false # test Erdos-Renyi baseline
  use_mask_prob: False
  num_vis: 20
  vis_num_row: 3 # visualize `num_vis` samples in `vis_num_row` rows
  better_vis: true
  test_model_dir: snapshot_model
  test_model_name: gran_DT.pth
